import { routes } from "@/config/routes";
import React, { lazy } from "react";

const components = {
  // Design System components
  Home: lazy(() => import("@/pages/HomePage")),
  GettingStarted: lazy(() => import("@/pages/GettingStartedPage")),
  Playground: lazy(() => import("@/pages/PlaygroundPage")),
  TestComponents: lazy(() => import("@/pages/TestComponentsPage")),
  AccordionDocs: lazy(() => import("@/pages/AccordionDocsPage")),
  AlertDocs: lazy(() => import("@/pages/AlertDocsPage")),
  AvatarDocs: lazy(() => import("@/pages/AvatarDocsPage")),
  BadgeDocs: lazy(() => import("@/pages/BadgeDocsPage")),
  BreadcrumbDocs: lazy(() => import("@/pages/BreadcrumbDocsPage")),
  ButtonDocs: lazy(() => import("@/pages/ButtonDocsPage")),
  BoxDocs: lazy(() => import("@/pages/BoxDocsPage")),
  CardDocs: lazy(() => import("@/pages/CardDocsPage")),
  ChartsDocs: lazy(() => import("@/pages/ChartsDocsPage")),
  CheckboxDocs: lazy(() => import("@/pages/CheckboxDocsPage")),
  ContainerDocs: lazy(() => import("@/pages/ContainerDocsPage")),
  CenterDocs: lazy(() => import("@/pages/CenterDocsPage")),
  SectionDocs: lazy(() => import("@/pages/SectionDocsPage")),
  SliderDocs: lazy(() => import("@/pages/SliderDocsPage")),
  RatingDocs: lazy(() => import("@/pages/RatingDocsPage")),
  CalendarDocs: lazy(() => import("@/pages/CalendarDocsPage")),
  EmptyStateDocs: lazy(() => import("@/pages/EmptyStateDocsPage")),
  MenuDocs: lazy(() => import("@/pages/MenuDocsPage")),
  SearchDocs: lazy(() => import("@/pages/SearchDocsPage")),
  AspectRatioDocs: lazy(() => import("@/pages/AspectRatioDocsPage")),
  SplitPaneDocs: lazy(() => import("@/pages/SplitPaneDocsPage")),
  StepperDocs: lazy(() => import("@/pages/StepperDocsPage")),
  ColorPickerDocs: lazy(() => import("@/pages/ColorPickerDocsPage")),
  ContextMenuDocs: lazy(() => import("@/pages/ContextMenuDocsPage")),
  DateRangePickerDocs: lazy(() => import("@/pages/DateRangePickerDocsPage")),
  FileUploadDocs: lazy(() => import("@/pages/FileUploadDocsPage")),
  FloatingActionButtonDocs: lazy(() => import("@/pages/FloatingActionButtonDocsPage")),
  OTPInputDocs: lazy(() => import("@/pages/OTPInputDocsPage")),
  PhoneInputDocs: lazy(() => import("@/pages/PhoneInputDocsPage")),
  TimePickerDocs: lazy(() => import("@/pages/TimePickerDocsPage")),
  SegmentedControlDocs: lazy(() => import("@/pages/SegmentedControlDocsPage")),
  TagInputDocs: lazy(() => import("@/pages/TagInputDocsPage")),
  SheetDocs: lazy(() => import("@/pages/SheetDocsPage")),
  BottomSheetDocs: lazy(() => import("@/pages/BottomSheetDocsPage")),
  TimelineDocs: lazy(() => import("@/pages/TimelineDocsPage")),
  TreeDocs: lazy(() => import("@/pages/TreeDocsPage")),
  TourDocs: lazy(() => import("@/pages/TourDocsPage")),
  GaugeDocs: lazy(() => import("@/pages/GaugeDocsPage")),
  StatCardDocs: lazy(() => import("@/pages/StatCardDocsPage")),
  MetricCardDocs: lazy(() => import("@/pages/MetricCardDocsPage")),
  StatusBadgeDocs: lazy(() => import("@/pages/StatusBadgeDocsPage")),
  SparklineDocs: lazy(() => import("@/pages/SparklineDocsPage")),
  BottomNavigationDocs: lazy(() => import("@/pages/BottomNavigationDocsPage")),
  InfiniteScrollDocs: lazy(() => import("@/pages/InfiniteScrollDocsPage")),
  StickyHeaderDocs: lazy(() => import("@/pages/StickyHeaderDocsPage")),
  SwipeActionsDocs: lazy(() => import("@/pages/SwipeActionsDocsPage")),
  TabBarDocs: lazy(() => import("@/pages/TabBarDocsPage")),
  VirtualTableDocs: lazy(() => import("@/pages/VirtualTableDocsPage")),
  WidgetDocs: lazy(() => import("@/pages/WidgetDocsPage")),
  WindowedListDocs: lazy(() => import("@/pages/WindowedListDocsPage")),
  ActionCenterDocs: lazy(() => import("@/pages/ActionCenterDocsPage")),
  ActivityFeedDocs: lazy(() => import("@/pages/ActivityFeedDocsPage")),
  HeatmapDocs: lazy(() => import("@/pages/HeatmapDocsPage")),
  RichTextEditorDocs: lazy(() => import("@/pages/RichTextEditorDocsPage")),
  TimelineChartDocs: lazy(() => import("@/pages/TimelineChartDocsPage")),
  TreeMapDocs: lazy(() => import("@/pages/TreeMapDocsPage")),
  ThemeTest: lazy(() => import("@/pages/ThemeTestPage")),
  DialogDocs: lazy(() => import("@/pages/DialogDocsPage")),
  DrawerDocs: lazy(() => import("@/pages/DrawerDocsPage")),
  DataTableDocs: lazy(() => import("@/pages/DataTableDocsPage")),
  FeedbackDocs: lazy(() => import("@/pages/FeedbackDocsPage")),
  FlexDocs: lazy(() => import("@/pages/FlexDocsPage")),
  FormDocs: lazy(() => import("@/pages/FormDocsPage")),
  GridDocs: lazy(() => import("@/pages/GridDocsPage")),
  InputDocs: lazy(() => import("@/pages/InputDocsPage")),
  IconsDocs: lazy(() => import("@/pages/IconsDocsPage")),
  ModalDocs: lazy(() => import("@/pages/ModalDocsPage")),
  NotificationCenterDocs: lazy(() => import("@/pages/NotificationCenterDocsPage")),
  NavigationDocs: lazy(() => import("@/pages/NavigationDocsPage")),
  NavbarDocs: lazy(() => import("@/pages/NavbarDocsPage")),
  HeroDocs: lazy(() => import("@/pages/HeroDocsPage")),
  FooterDocs: lazy(() => import("@/pages/FooterDocsPage")),
  PaginationDocs: lazy(() => import("@/pages/PaginationDocsPage")),
  PopoverDocs: lazy(() => import("@/pages/PopoverDocsPage")),
  RadioDocs: lazy(() => import("@/pages/RadioDocsPage")),
  ScrollAreaDocs: lazy(() => import("@/pages/ScrollAreaDocsPage")),
  SelectDocs: lazy(() => import("@/pages/SelectDocsPage")),
  SelectWithSearchDocs: lazy(() => import("@/pages/SelectWithSearchDocsPage")),
  SidebarDocs: lazy(() => import("@/pages/SidebarDocsPage")),
  StackDocs: lazy(() => import("@/pages/StackDocsPage")),
  SwitchDocs: lazy(() => import("@/pages/SwitchDocsPage")),
  TableDocs: lazy(() => import("@/pages/TableDocsPage")),
  TabsDocs: lazy(() => import("@/pages/TabsDocsPage")),
  TextareaDocs: lazy(() => import("@/pages/TextareaDocsPage")),
  ToastDocs: lazy(() => import("@/pages/ToastDocsPage")),
  TooltipDocs: lazy(() => import("@/pages/TooltipDocsPage")),
  ThemingDocs: lazy(() => import("@/pages/ThemingDocsPage")),
  TypographyDocs: lazy(() => import("@/pages/TypographyDocsPage")),
  HooksDocs: lazy(() => import("@/pages/HooksDocsPage")),
  LLMDocs: lazy(() => import("@/pages/LLMDocsPage")),
  CLIDocs: lazy(() => import("@/pages/CLIDocsPage")),
  CodeGenerationDocs: lazy(() => import("@/pages/CodeGenerationDocsPage")),
  VSCodeExtensionDocs: lazy(() => import("@/pages/VSCodeExtensionDocsPage")),
};

// Route mapping for easy access
const routeComponents = {
  // Design System routes
  [routes.home]: components.Home,
  [routes.gettingStarted]: components.GettingStarted,
  [routes.playground]: components.Playground,
  [routes.testComponents]: components.TestComponents,
  [routes.accordionDocs]: components.AccordionDocs,
  [routes.alertDocs]: components.AlertDocs,
  [routes.avatarDocs]: components.AvatarDocs,
  [routes.badgeDocs]: components.BadgeDocs,
  [routes.breadcrumbDocs]: components.BreadcrumbDocs,
  [routes.buttonDocs]: components.ButtonDocs,
  [routes.boxDocs]: components.BoxDocs,
  [routes.cardDocs]: components.CardDocs,
  [routes.chartsDocs]: components.ChartsDocs,
  [routes.checkboxDocs]: components.CheckboxDocs,
  [routes.containerDocs]: components.ContainerDocs,
  [routes.centerDocs]: components.CenterDocs,
  [routes.sectionDocs]: components.SectionDocs,
  [routes.sliderDocs]: components.SliderDocs,
  [routes.ratingDocs]: components.RatingDocs,
  [routes.calendarDocs]: components.CalendarDocs,
  [routes.emptyStateDocs]: components.EmptyStateDocs,
  [routes.menuDocs]: components.MenuDocs,
  [routes.searchDocs]: components.SearchDocs,
  [routes.aspectRatioDocs]: components.AspectRatioDocs,
  [routes.splitPaneDocs]: components.SplitPaneDocs,
  [routes.stepperDocs]: components.StepperDocs,
  [routes.colorPickerDocs]: components.ColorPickerDocs,
  [routes.contextMenuDocs]: components.ContextMenuDocs,
  [routes.dateRangePickerDocs]: components.DateRangePickerDocs,
  [routes.fileUploadDocs]: components.FileUploadDocs,
  [routes.floatingActionButtonDocs]: components.FloatingActionButtonDocs,
  [routes.otpInputDocs]: components.OTPInputDocs,
  [routes.phoneInputDocs]: components.PhoneInputDocs,
  [routes.timePickerDocs]: components.TimePickerDocs,
  [routes.segmentedControlDocs]: components.SegmentedControlDocs,
  [routes.tagInputDocs]: components.TagInputDocs,
  [routes.sheetDocs]: components.SheetDocs,
  [routes.bottomSheetDocs]: components.BottomSheetDocs,
  [routes.timelineDocs]: components.TimelineDocs,
  [routes.treeDocs]: components.TreeDocs,
  [routes.tourDocs]: components.TourDocs,
  [routes.gaugeDocs]: components.GaugeDocs,
  [routes.statCardDocs]: components.StatCardDocs,
  [routes.metricCardDocs]: components.MetricCardDocs,
  [routes.statusBadgeDocs]: components.StatusBadgeDocs,
  [routes.sparklineDocs]: components.SparklineDocs,
  [routes.bottomNavigationDocs]: components.BottomNavigationDocs,
  [routes.infiniteScrollDocs]: components.InfiniteScrollDocs,
  [routes.stickyHeaderDocs]: components.StickyHeaderDocs,
  [routes.swipeActionsDocs]: components.SwipeActionsDocs,
  [routes.tabBarDocs]: components.TabBarDocs,
  [routes.virtualTableDocs]: components.VirtualTableDocs,
  [routes.widgetDocs]: components.WidgetDocs,
  [routes.windowedListDocs]: components.WindowedListDocs,
  [routes.actionCenterDocs]: components.ActionCenterDocs,
  [routes.activityFeedDocs]: components.ActivityFeedDocs,
  [routes.heatmapDocs]: components.HeatmapDocs,
  [routes.richTextEditorDocs]: components.RichTextEditorDocs,
  [routes.timelineChartDocs]: components.TimelineChartDocs,
  [routes.treeMapDocs]: components.TreeMapDocs,
  [routes.themeTest]: components.ThemeTest,
  [routes.dialogDocs]: components.DialogDocs,
  [routes.drawerDocs]: components.DrawerDocs,
  [routes.datatableDocs]: components.DataTableDocs,
  [routes.feedbackDocs]: components.FeedbackDocs,
  [routes.flexDocs]: components.FlexDocs,
  [routes.formDocs]: components.FormDocs,
  [routes.gridDocs]: components.GridDocs,
  [routes.inputDocs]: components.InputDocs,
  [routes.iconsDocs]: components.IconsDocs,
  [routes.modalDocs]: components.ModalDocs,
  [routes.notificationCenterDocs]: components.NotificationCenterDocs,
  [routes.navigationDocs]: components.NavigationDocs,
  [routes.navbarDocs]: components.NavbarDocs,
  [routes.heroDocs]: components.HeroDocs,
  [routes.footerDocs]: components.FooterDocs,
  [routes.paginationDocs]: components.PaginationDocs,
  [routes.popoverDocs]: components.PopoverDocs,
  [routes.radioDocs]: components.RadioDocs,
  [routes.scrollAreaDocs]: components.ScrollAreaDocs,
  [routes.selectDocs]: components.SelectDocs,
  [routes.selectWithSearchDocs]: components.SelectWithSearchDocs,
  [routes.sidebarDocs]: components.SidebarDocs,
  [routes.stackDocs]: components.StackDocs,
  [routes.switchDocs]: components.SwitchDocs,
  [routes.tableDocs]: components.TableDocs,
  [routes.tabsDocs]: components.TabsDocs,
  [routes.textareaDocs]: components.TextareaDocs,
  [routes.toastDocs]: components.ToastDocs,
  [routes.tooltipDocs]: components.TooltipDocs,
  [routes.themingDocs]: components.ThemingDocs,
  [routes.typographyDocs]: components.TypographyDocs,
  [routes.hooksDocs]: components.HooksDocs,
  [routes.llmResource]: components.LLMDocs,
  [routes.cliDocs]: components.CLIDocs,
  [routes.codeGenerationDocs]: components.CodeGenerationDocs,
  [routes.vscodeExtensionDocs]: components.VSCodeExtensionDocs,
};

// Static routes
const staticRoutes = (Object.keys(routeComponents) as Array<keyof typeof routeComponents>).map(
  (path) => ({
    path: path as string,
    element: React.createElement(routeComponents[path]),
  }),
);

// All routes combined
export const allRoutes = [...staticRoutes];

// Export individual route arrays for different purposes
export const publicRoutes = staticRoutes.filter(
  ({ path }: { path: string }) =>
    path === routes.home || path === routes.components || path === routes.playground,
);

export interface RouteConfig {
  path: string;
  element: React.ReactElement;
}

export const protectedRoutes: RouteConfig[] = [];

export const authRoutes: RouteConfig[] = [];

export { routes, components, routeComponents };
