export const routes = {
	// Design System routes
	home: '/',
	components: '/components',
	gettingStarted: '/components/getting-started',
	playground: '/playground',
	testComponents: '/test-components',
	accordionDocs: '/components/docs/accordion',
	alertDocs: '/components/docs/alert',
	avatarDocs: '/components/docs/avatar',
	badgeDocs: '/components/docs/badge',
	breadcrumbDocs: '/components/docs/breadcrumb',
	buttonDocs: '/components/docs/button',
	cardDocs: '/components/docs/card',
	chartsDocs: '/components/docs/charts',
	checkboxDocs: '/components/docs/checkbox',
	dialogDocs: '/components/docs/dialog',
	drawerDocs: '/components/docs/drawer',
	datatableDocs: '/components/docs/datatable',
	formDocs: '/components/docs/form',
	inputDocs: '/components/docs/input',
	modalDocs: '/components/docs/modal',
	navigationDocs: '/components/docs/navigation',
	paginationDocs: '/components/docs/pagination',
	popoverDocs: '/components/docs/popover',
	radioDocs: '/components/docs/radio',
	scrollAreaDocs: '/components/docs/scrollarea',
	selectDocs: '/components/docs/select',
	sidebarDocs: '/components/docs/sidebar',
	switchDocs: '/components/docs/switch',
	tableDocs: '/components/docs/table',
	tabsDocs: '/components/docs/tabs',
	textareaDocs: '/components/docs/textarea',
	toastDocs: '/components/docs/toast',
	tooltipDocs: '/components/docs/tooltip',
};
